-- =====================================================
-- MIGRACIÓN: Traducir ejercicios del dataset a español
-- =====================================================
-- Descripción: Traduce muscle_group y nombres de ejercicios
-- del inglés al español para que coincidan con la UI
-- =====================================================

-- 1. Traducir muscle_group a español
UPDATE exercises SET muscle_group = 'Pecho' WHERE muscle_group = 'chest';
UPDATE exercises SET muscle_group = 'Espalda' WHERE muscle_group = 'back';
UPDATE exercises SET muscle_group = 'Hombros' WHERE muscle_group = 'shoulders';
UPDATE exercises SET muscle_group = 'Brazos' WHERE muscle_group = 'upper arms';
UPDATE exercises SET muscle_group = 'Piernas' WHERE muscle_group = 'upper legs';
UPDATE exercises SET muscle_group = 'Antebrazos' WHERE muscle_group = 'lower arms';
UPDATE exercises SET muscle_group = 'Pantorrillas' WHERE muscle_group = 'lower legs';
UPDATE exercises SET muscle_group = 'Core' WHERE muscle_group = 'waist';
UPDATE exercises SET muscle_group = 'Cuello' WHERE muscle_group = 'neck';
UPDATE exercises SET muscle_group = 'Cardio' WHERE muscle_group = 'cardio';

-- 2. Traducir nombres de ejercicios a español
UPDATE exercises SET name = CASE
  -- Abdominales / Core
  WHEN name = '3/4 sit-up' THEN 'abdominal 3/4'
  WHEN name = '45° side bend' THEN 'flexión lateral 45°'
  WHEN name = 'air bike' THEN 'bicicleta en el aire'
  WHEN name = 'alternate heel touchers' THEN 'toque de talones alterno'
  WHEN name = 'arms overhead full sit-up (male)' THEN 'abdominal completo con brazos arriba'
  WHEN name = 'assisted hanging knee raise' THEN 'elevación de rodillas colgado asistido'
  WHEN name = 'assisted hanging knee raise with throw down' THEN 'elevación de rodillas con lanzamiento asistido'
  WHEN name = 'assisted lying leg raise with lateral throw down' THEN 'elevación de piernas con lanzamiento lateral asistido'
  WHEN name = 'assisted lying leg raise with throw down' THEN 'elevación de piernas con lanzamiento asistido'
  WHEN name = 'assisted motion russian twist' THEN 'giro ruso asistido'
  WHEN name = 'assisted sit-up' THEN 'abdominal asistido'
  WHEN name = 'band alternating v-up' THEN 'v-up alterno con banda'
  WHEN name = 'band assisted wheel rollerout' THEN 'rueda abdominal asistida con banda'
  WHEN name = 'band bicycle crunch' THEN 'bicicleta crunch con banda'
  WHEN name = 'band horizontal pallof press' THEN 'press pallof horizontal con banda'
  WHEN name = 'band jack knife sit-up' THEN 'navaja abdominal con banda'
  WHEN name = 'band kneeling twisting crunch' THEN 'crunch de rodillas con giro y banda'
  WHEN name = 'band lying straight leg raise' THEN 'elevación de piernas rectas con banda'
  WHEN name = 'cable crunch' THEN 'crunch en polea'
  WHEN name = 'captains chair leg raise' THEN 'elevación de piernas en silla capitán'
  WHEN name = 'chair leg raise' THEN 'elevación de piernas en silla'
  WHEN name = 'crunch (arms crossed)' THEN 'crunch con brazos cruzados'
  WHEN name = 'crunch (hands overhead)' THEN 'crunch con manos arriba'
  WHEN name = 'crunch floor' THEN 'crunch en el suelo'
  WHEN name = 'dead bug' THEN 'insecto muerto'
  WHEN name = 'elbow plank' THEN 'plancha de codos'
  WHEN name = 'flutter kicks' THEN 'patadas alternas'
  WHEN name = 'front plank' THEN 'plancha frontal'
  WHEN name = 'side plank' THEN 'plancha lateral'
  WHEN name = 'weighted side plank' THEN 'plancha lateral con peso'
  WHEN name = 'hanging knee raise' THEN 'elevación de rodillas colgado'
  WHEN name = 'hanging leg raise' THEN 'elevación de piernas colgado'
  WHEN name = 'hanging pike' THEN 'pike colgado'
  WHEN name = 'hip raises (butt kick)' THEN 'elevación de cadera (patada de glúteo)'
  WHEN name = 'hip tap' THEN 'toque de cadera'
  WHEN name = 'jack knife sit-up' THEN 'navaja abdominal'
  WHEN name = 'jack knife sit-up (male)' THEN 'navaja abdominal'
  WHEN name = 'knee raise' THEN 'elevación de rodillas'
  WHEN name = 'kneeling cable crunch' THEN 'crunch de rodillas en polea'
  WHEN name = 'leg pull in' THEN 'jalón de piernas'
  WHEN name = 'leg pull in (male)' THEN 'jalón de piernas'
  WHEN name = 'leg raise' THEN 'elevación de piernas'
  WHEN name = 'london bridge (male)' THEN 'puente de londres'
  WHEN name = 'long arm crunch' THEN 'crunch con brazos largos'
  WHEN name = 'lying leg raise' THEN 'elevación de piernas acostado'
  WHEN name = 'lying twisting leg raise' THEN 'elevación de piernas con giro acostado'
  WHEN name = 'mountain climber' THEN 'escalador'
  WHEN name = 'oblique crunch' THEN 'crunch oblicuo'
  WHEN name = 'oblique crunch (male)' THEN 'crunch oblicuo'
  WHEN name = 'pelvic tilt' THEN 'inclinación pélvica'
  WHEN name = 'plank' THEN 'plancha'
  WHEN name = 'reverse crunch' THEN 'crunch inverso'
  WHEN name = 'russian twist' THEN 'giro ruso'
  WHEN name = 'russian twist (male)' THEN 'giro ruso'
  WHEN name = 'seated leg raise' THEN 'elevación de piernas sentado'
  WHEN name = 'side bridge' THEN 'puente lateral'
  WHEN name = 'side bridge hip abduction (male)' THEN 'puente lateral con abducción de cadera'
  WHEN name = 'side hip (on floor)' THEN 'cadera lateral en el suelo'
  WHEN name = 'side leg raise' THEN 'elevación lateral de pierna'
  WHEN name = 'sit-up' THEN 'abdominal'
  WHEN name = 'standing cable crunch' THEN 'crunch de pie en polea'
  WHEN name = 'standing twisting cable crunch' THEN 'crunch de pie con giro en polea'
  WHEN name = 'straight leg raise' THEN 'elevación de piernas rectas'
  WHEN name = 'trunk rotation on stability ball' THEN 'rotación de tronco en pelota'
  WHEN name = 'tuck crunch' THEN 'crunch agrupado'
  WHEN name = 'twisting crunch' THEN 'crunch con giro'
  WHEN name = 'weighted kneeling crescent kick' THEN 'patada creciente de rodillas con peso'
  WHEN name = 'wheel rollerout' THEN 'rueda abdominal'
  WHEN name = 'band horizontal pallof press (male)' THEN 'press pallof horizontal con banda'
  WHEN name = 'cable seated crunch' THEN 'crunch sentado en polea'
  WHEN name = 'captains chair straight leg raise' THEN 'elevación de piernas rectas en silla capitán'
  WHEN name = 'crunches' THEN 'crunches'
  WHEN name = 'hanging leg raise (male)' THEN 'elevación de piernas colgado'
  WHEN name = 'jackknife sit-up' THEN 'navaja abdominal'
  WHEN name = 'leg up hamstring stretch' THEN 'estiramiento de femoral con pierna arriba'
  WHEN name = 'reverse crunch (male)' THEN 'crunch inverso'
  WHEN name = 'arm slingers hanging bent knee legs' THEN 'elevación de rodillas colgado'

  -- Espalda
  WHEN name = 'alternate lateral pulldown' THEN 'jalón lateral alterno'
  WHEN name = 'archer pull up' THEN 'dominada de arquero'
  WHEN name = 'assisted parallel close grip pull-up' THEN 'dominada paralela agarre cerrado asistido'
  WHEN name = 'assisted pull-up' THEN 'dominada asistida'
  WHEN name = 'assisted standing chin-up' THEN 'dominada supina de pie asistido'
  WHEN name = 'assisted standing pull-up' THEN 'dominada de pie asistido'
  WHEN name = 'back extension on exercise ball' THEN 'extensión de espalda en pelota'
  WHEN name = 'back lever' THEN 'palanca trasera'
  WHEN name = 'back pec stretch' THEN 'estiramiento de espalda y pectoral'
  WHEN name = 'band assisted pull-up' THEN 'dominada asistida con banda'
  WHEN name = 'band bent-over hip extension' THEN 'extensión de cadera inclinado con banda'
  WHEN name = 'band close-grip pulldown' THEN 'jalón agarre cerrado con banda'
  WHEN name = 'band fixed back close grip pulldown' THEN 'jalón agarre cerrado espalda fija con banda'
  WHEN name = 'band fixed back underhand pulldown' THEN 'jalón supino espalda fija con banda'
  WHEN name = 'band kneeling one arm pulldown' THEN 'jalón un brazo de rodillas con banda'
  WHEN name = 'band reverse fly' THEN 'apertura invertida con banda'
  WHEN name = 'band seated row' THEN 'remo sentado con banda'
  WHEN name = 'band straight back seated row' THEN 'remo sentado espalda recta con banda'
  WHEN name = 'band straight leg deadlift' THEN 'peso muerto piernas rectas con banda'
  WHEN name = 'barbell deadlift' THEN 'peso muerto con barra'
  WHEN name = 'barbell bent over row' THEN 'remo inclinado con barra'
  WHEN name = 'barbell row' THEN 'remo con barra'
  WHEN name = 'bent over barbell row' THEN 'remo inclinado con barra'
  WHEN name = 'bent over dumbbell row' THEN 'remo inclinado con mancuerna'
  WHEN name = 'bent over one arm long bar row' THEN 'remo inclinado un brazo con barra larga'
  WHEN name = 'bent over two arm long bar row' THEN 'remo inclinado dos brazos con barra larga'
  WHEN name = 'bent over two dumbbell row' THEN 'remo inclinado con dos mancuernas'
  WHEN name = 'cable seated row' THEN 'remo sentado en polea'
  WHEN name = 'cable straight arm pulldown' THEN 'jalón de brazo recto en polea'
  WHEN name = 'cat stretch' THEN 'estiramiento de gato'
  WHEN name = 'chin-up' THEN 'dominada supina'
  WHEN name = 'close grip chin up' THEN 'dominada supina agarre cerrado'
  WHEN name = 'close grip pull up' THEN 'dominada agarre cerrado'
  WHEN name = 'deadlift' THEN 'peso muerto'
  WHEN name = 'deadlift (male)' THEN 'peso muerto'
  WHEN name = 'dumbbell pullover' THEN 'pullover con mancuerna'
  WHEN name = 'face pull' THEN 'face pull'
  WHEN name = 'hyperextension' THEN 'hiperextensión'
  WHEN name = 'inverted row' THEN 'remo invertido'
  WHEN name = 'lat pulldown' THEN 'jalón al pecho'
  WHEN name = 'lat pulldown (male)' THEN 'jalón al pecho'
  WHEN name = 'one arm dumbbell row' THEN 'remo un brazo con mancuerna'
  WHEN name = 'one arm lat pulldown' THEN 'jalón un brazo'
  WHEN name = 'pull up' THEN 'dominada'
  WHEN name = 'reverse fly' THEN 'apertura invertida'
  WHEN name = 'reverse fly (male)' THEN 'apertura invertida'
  WHEN name = 'roman chair hyperextension' THEN 'hiperextensión en silla romana'
  WHEN name = 'seated cable row' THEN 'remo sentado en polea'
  WHEN name = 'seated cable row (male)' THEN 'remo sentado en polea'
  WHEN name = 'straight arm pulldown' THEN 'jalón de brazo recto'
  WHEN name = 'superman' THEN 'superman'
  WHEN name = 't-bar row' THEN 'remo t-bar'
  WHEN name = 'twin handle parallel lat pull down' THEN 'jalón al pecho con agarre paralelo'
  WHEN name = 'v-bar pulldown' THEN 'jalón con barra v'
  WHEN name = 'wide grip chin up' THEN 'dominada supina agarre ancho'
  WHEN name = 'wide grip lat pulldown' THEN 'jalón al pecho agarre ancho'
  WHEN name = 'wide grip pull up' THEN 'dominada agarre ancho'
  WHEN name = 'weighted pull up' THEN 'dominada con peso'
  WHEN name = 'weighted chin up' THEN 'dominada supina con peso'

  -- Pecho
  WHEN name = 'archer push up' THEN 'flexión de arquero'
  WHEN name = 'assisted chest dip (kneeling)' THEN 'fondo de pecho asistido (arrodillado)'
  WHEN name = 'assisted seated pectoralis major stretch with stability ball' THEN 'estiramiento de pectoral sentado con pelota'
  WHEN name = 'assisted wide-grip chest dip (kneeling)' THEN 'fondo de pecho agarre ancho asistido'
  WHEN name = 'band bench press' THEN 'press de banca con banda'
  WHEN name = 'band close-grip push-up' THEN 'flexión agarre cerrado con banda'
  WHEN name = 'barbell bench press' THEN 'press de banca con barra'
  WHEN name = 'barbell bench press (male)' THEN 'press de banca con barra'
  WHEN name = 'bench press' THEN 'press de banca'
  WHEN name = 'cable crossover' THEN 'cruce de poleas'
  WHEN name = 'cable fly' THEN 'apertura en polea'
  WHEN name = 'chest dip' THEN 'fondo de pecho'
  WHEN name = 'close grip bench press' THEN 'press de banca agarre cerrado'
  WHEN name = 'decline barbell bench press' THEN 'press de banca declinado con barra'
  WHEN name = 'decline bench press' THEN 'press de banca declinado'
  WHEN name = 'decline dumbbell bench press' THEN 'press de banca declinado con mancuerna'
  WHEN name = 'decline push up' THEN 'flexión declinada'
  WHEN name = 'dumbbell bench press' THEN 'press de banca con mancuerna'
  WHEN name = 'dumbbell fly' THEN 'apertura con mancuerna'
  WHEN name = 'dumbbell fly (male)' THEN 'apertura con mancuerna'
  WHEN name = 'incline barbell bench press' THEN 'press de banca inclinado con barra'
  WHEN name = 'incline bench press' THEN 'press de banca inclinado'
  WHEN name = 'incline dumbbell bench press' THEN 'press de banca inclinado con mancuerna'
  WHEN name = 'incline dumbbell fly' THEN 'apertura inclinada con mancuerna'
  WHEN name = 'incline push up' THEN 'flexión inclinada'
  WHEN name = 'kneeling push up' THEN 'flexión de rodillas'
  WHEN name = 'low cable crossover' THEN 'cruce de poleas bajo'
  WHEN name = 'machine bench press' THEN 'press de banca en máquina'
  WHEN name = 'pec deck fly' THEN 'apertura en pectoral'
  WHEN name = 'push up' THEN 'flexión'
  WHEN name = 'push up (male)' THEN 'flexión'
  WHEN name = 'ring dips (male)' THEN 'fondos en anillas'
  WHEN name = 'seated cable fly' THEN 'apertura sentado en polea'
  WHEN name = 'smith machine bench press' THEN 'press de banca en smith'
  WHEN name = 'standing dumbbell fly (male)' THEN 'apertura de pie con mancuerna'
  WHEN name = 'svend press' THEN 'press svend'
  WHEN name = 'wide grip bench press' THEN 'press de banca agarre ancho'
  WHEN name = 'wide hand push up' THEN 'flexión con brazos abiertos'

  -- Hombros
  WHEN name = 'alternating dumbbell front raise' THEN 'elevación frontal alterna con mancuerna'
  WHEN name = 'band front lateral raise' THEN 'elevación frontal lateral con banda'
  WHEN name = 'band front raise' THEN 'elevación frontal con banda'
  WHEN name = 'barbell front raise' THEN 'elevación frontal con barra'
  WHEN name = 'barbell overhead press' THEN 'press militar con barra'
  WHEN name = 'barbell seated overhead press' THEN 'press militar sentado con barra'
  WHEN name = 'barbell shoulder press' THEN 'press de hombros con barra'
  WHEN name = 'bent over dumbbell lateral raise' THEN 'elevación lateral inclinado con mancuerna'
  WHEN name = 'cable front raise' THEN 'elevación frontal en polea'
  WHEN name = 'cable lateral raise' THEN 'elevación lateral en polea'
  WHEN name = 'clean and press' THEN 'cargada y press'
  WHEN name = 'dumbbell front raise' THEN 'elevación frontal con mancuerna'
  WHEN name = 'dumbbell lateral raise' THEN 'elevación lateral con mancuerna'
  WHEN name = 'dumbbell shoulder press' THEN 'press de hombros con mancuerna'
  WHEN name = 'dumbbell shoulder press (male)' THEN 'press de hombros con mancuerna'
  WHEN name = 'front raise' THEN 'elevación frontal'
  WHEN name = 'incline dumbbell front raise (male)' THEN 'elevación frontal inclinado con mancuerna'
  WHEN name = 'lateral raise' THEN 'elevación lateral'
  WHEN name = 'machine shoulder press' THEN 'press de hombros en máquina'
  WHEN name = 'one arm dumbbell front raise (male)' THEN 'elevación frontal un brazo con mancuerna'
  WHEN name = 'rear delt fly' THEN 'apertura de deltoides posterior'
  WHEN name = 'rear delt row' THEN 'remo de deltoides posterior'
  WHEN name = 'seated barbell overhead press' THEN 'press militar sentado con barra'
  WHEN name = 'seated dumbbell lateral raise' THEN 'elevación lateral sentado con mancuerna'
  WHEN name = 'seated dumbbell shoulder press' THEN 'press de hombros sentado con mancuerna'
  WHEN name = 'shoulder raise' THEN 'elevación de hombros'
  WHEN name = 'shoulder shrug' THEN 'encogimiento de hombros'
  WHEN name = 'smith machine overhead press' THEN 'press militar en smith'
  WHEN name = 'standing dumbbell lateral raise' THEN 'elevación lateral de pie con mancuerna'
  WHEN name = 'standing dumbbell press' THEN 'press de pie con mancuerna'
  WHEN name = 'upright row' THEN 'remo vertical'
  WHEN name = 'dumbbell clean and press (male)' THEN 'cargada y press con mancuerna'

  -- Bíceps
  WHEN name = 'alternating dumbbell biceps curl' THEN 'curl de bíceps alterno con mancuerna'
  WHEN name = 'band alternating biceps curl' THEN 'curl de bíceps alterno con banda'
  WHEN name = 'band concentration curl' THEN 'curl concentrado con banda'
  WHEN name = 'band one arm overhead biceps curl' THEN 'curl de bíceps por encima un brazo con banda'
  WHEN name = 'barbell biceps curl' THEN 'curl de bíceps con barra'
  WHEN name = 'barbell curl' THEN 'curl con barra'
  WHEN name = 'biceps curl' THEN 'curl de bíceps'
  WHEN name = 'biceps curl (male)' THEN 'curl de bíceps'
  WHEN name = 'cable biceps curl' THEN 'curl de bíceps en polea'
  WHEN name = 'concentration curl' THEN 'curl concentrado'
  WHEN name = 'dumbbell biceps curl' THEN 'curl de bíceps con mancuerna'
  WHEN name = 'dumbbell concentration curl' THEN 'curl concentrado con mancuerna'
  WHEN name = 'dumbbell hammer curl' THEN 'curl martillo con mancuerna'
  WHEN name = 'ez bar biceps curl' THEN 'curl de bíceps con barra ez'
  WHEN name = 'ez bar curl' THEN 'curl con barra ez'
  WHEN name = 'hammer curl' THEN 'curl martillo'
  WHEN name = 'incline dumbbell biceps curl (male)' THEN 'curl de bíceps inclinado con mancuerna'
  WHEN name = 'one arm cable biceps curl' THEN 'curl de bíceps un brazo en polea'
  WHEN name = 'preacher curl' THEN 'curl en banco predicador'
  WHEN name = 'reverse barbell curl' THEN 'curl inverso con barra'
  WHEN name = 'reverse curl' THEN 'curl inverso'
  WHEN name = 'rope biceps curl (male)' THEN 'curl de bíceps con cuerda'
  WHEN name = 'seated biceps curl (male)' THEN 'curl de bíceps sentado'
  WHEN name = 'spider curl' THEN 'curl araña'
  WHEN name = 'standing biceps cable curl (male)' THEN 'curl de bíceps de pie en polea'
  WHEN name = 'standing dumbbell biceps curl (male)' THEN 'curl de bíceps de pie con mancuerna'

  -- Tríceps
  WHEN name = 'assisted standing triceps extension (with towel)' THEN 'extensión de tríceps de pie con toalla asistido'
  WHEN name = 'assisted triceps dip (kneeling)' THEN 'fondo de tríceps asistido (arrodillado)'
  WHEN name = 'barbell triceps extension' THEN 'extensión de tríceps con barra'
  WHEN name = 'bench dip' THEN 'fondo en banca'
  WHEN name = 'bench dip (male)' THEN 'fondo en banca'
  WHEN name = 'cable kickback' THEN 'patada de tríceps en polea'
  WHEN name = 'cable overhead triceps extension' THEN 'extensión de tríceps por encima en polea'
  WHEN name = 'close grip push up' THEN 'flexión agarre cerrado'
  WHEN name = 'diamond push up' THEN 'flexión diamante'
  WHEN name = 'dumbbell kickback' THEN 'patada de tríceps con mancuerna'
  WHEN name = 'dumbbell triceps extension' THEN 'extensión de tríceps con mancuerna'
  WHEN name = 'ez bar triceps extension (male)' THEN 'extensión de tríceps con barra ez'
  WHEN name = 'ez bar skullcrusher' THEN 'skullcrusher con barra ez'
  WHEN name = 'lying triceps extension' THEN 'extensión de tríceps acostado'
  WHEN name = 'one arm dumbbell triceps extension (male)' THEN 'extensión de tríceps un brazo con mancuerna'
  WHEN name = 'overhead triceps extension' THEN 'extensión de tríceps por encima'
  WHEN name = 'pushdown' THEN 'jalón de tríceps'
  WHEN name = 'rope pushdown' THEN 'jalón de tríceps con cuerda'
  WHEN name = 'seated triceps extension (male)' THEN 'extensión de tríceps sentado'
  WHEN name = 'skullcrusher' THEN 'skullcrusher'
  WHEN name = 'triceps dip' THEN 'fondo de tríceps'
  WHEN name = 'triceps extension' THEN 'extensión de tríceps'
  WHEN name = 'triceps pushdown' THEN 'jalón de tríceps'
  WHEN name = 'triceps pushdown (male)' THEN 'jalón de tríceps'
  WHEN name = 'v-bar pushdown' THEN 'jalón de tríceps con barra v'
  WHEN name = 'weighted bench dip' THEN 'fondo en banca con peso'

  -- Piernas / Cuádriceps
  WHEN name = 'all fours squad stretch' THEN 'estiramiento de cuádriceps en cuatro patas'
  WHEN name = 'arms apart circular toe touch (male)' THEN 'toque de puntas con brazos abiertos'
  WHEN name = 'assisted lying glutes stretch' THEN 'estiramiento de glúteos acostado asistido'
  WHEN name = 'assisted lying gluteus and piriformis stretch' THEN 'estiramiento de glúteo y piramidal acostado asistido'
  WHEN name = 'assisted prone hamstring' THEN 'femoral boca abajo asistido'
  WHEN name = 'assisted prone lying quads stretch' THEN 'estiramiento de cuádriceps boca abajo asistido'
  WHEN name = 'assisted prone rectus femoris stretch' THEN 'estiramiento de recto femoral asistido'
  WHEN name = 'assisted side lying adductor stretch' THEN 'estiramiento de aductores acostado de lado asistido'
  WHEN name = 'backward jump' THEN 'salto hacia atrás'
  WHEN name = 'balance board' THEN 'tabla de equilibrio'
  WHEN name = 'band hip lift' THEN 'elevación de cadera con banda'
  WHEN name = 'band lying hip internal rotation' THEN 'rotación interna de cadera acostado con banda'
  WHEN name = 'band one leg squat (male)' THEN 'sentadilla una pierna con banda'
  WHEN name = 'band squat' THEN 'sentadilla con banda'
  WHEN name = 'band squat row' THEN 'sentadilla con remo y banda'
  WHEN name = 'barbell front squat' THEN 'sentadilla frontal con barra'
  WHEN name = 'barbell full squat' THEN 'sentadilla completa con barra'
  WHEN name = 'barbell hack squat' THEN 'sentadilla hack con barra'
  WHEN name = 'barbell lunge' THEN 'zancada con barra'
  WHEN name = 'barbell rear lunge' THEN 'zancada trasera con barra'
  WHEN name = 'barbell side lunge' THEN 'zancada lateral con barra'
  WHEN name = 'barbell squat' THEN 'sentadilla con barra'
  WHEN name = 'barbell squat (male)' THEN 'sentadilla con barra'
  WHEN name = 'barbell step up' THEN 'paso arriba con barra'
  WHEN name = 'barbell walking lunge' THEN 'zancada caminando con barra'
  WHEN name = 'bodyweight squat' THEN 'sentadilla con peso corporal'
  WHEN name = 'box squat' THEN 'sentadilla en cajón'
  WHEN name = 'bulgarian split squat' THEN 'sentadilla búlgara'
  WHEN name = 'curtsy lunge' THEN 'zancada de reverencia'
  WHEN name = 'dumbbell goblet squat' THEN 'sentadilla goblet con mancuerna'
  WHEN name = 'dumbbell lunge' THEN 'zancada con mancuerna'
  WHEN name = 'dumbbell squat' THEN 'sentadilla con mancuerna'
  WHEN name = 'dumbbell step up' THEN 'paso arriba con mancuerna'
  WHEN name = 'dumbbell walking lunge' THEN 'zancada caminando con mancuerna'
  WHEN name = 'forward jump' THEN 'salto hacia adelante'
  WHEN name = 'front squat' THEN 'sentadilla frontal'
  WHEN name = 'goblet squat' THEN 'sentadilla goblet'
  WHEN name = 'hack squat' THEN 'sentadilla hack'
  WHEN name = 'hip abduction' THEN 'abducción de cadera'
  WHEN name = 'hip adduction' THEN 'aducción de cadera'
  WHEN name = 'hip flexor stretch' THEN 'estiramiento de flexores de cadera'
  WHEN name = 'hip thrust' THEN 'empuje de cadera'
  WHEN name = 'kettlebell swing' THEN 'balanceo con pesa rusa'
  WHEN name = 'leg extension' THEN 'extensión de piernas'
  WHEN name = 'leg extension (male)' THEN 'extensión de piernas'
  WHEN name = 'leg press' THEN 'prensa de piernas'
  WHEN name = 'leg press (male)' THEN 'prensa de piernas'
  WHEN name = 'lunge' THEN 'zancada'
  WHEN name = 'lunge (male)' THEN 'zancada'
  WHEN name = 'one leg squat' THEN 'sentadilla una pierna'
  WHEN name = 'rear lunge' THEN 'zancada trasera'
  WHEN name = 'reverse lunge' THEN 'zancada inversa'
  WHEN name = 'reverse lunge (male)' THEN 'zancada inversa'
  WHEN name = 'side lunge' THEN 'zancada lateral'
  WHEN name = 'single leg squat (male)' THEN 'sentadilla una pierna'
  WHEN name = 'split squat' THEN 'sentadilla dividida'
  WHEN name = 'squat' THEN 'sentadilla'
  WHEN name = 'squat (male)' THEN 'sentadilla'
  WHEN name = 'step up' THEN 'paso arriba'
  WHEN name = 'walking lunge' THEN 'zancada caminando'
  WHEN name = 'wall sit' THEN 'sentadilla contra la pared'
  WHEN name = 'weighted squat' THEN 'sentadilla con peso'
  WHEN name = 'weighted walking lunge' THEN 'zancada caminando con peso'

  -- Femorales
  WHEN name = 'barbell deadlift (male)' THEN 'peso muerto con barra'
  WHEN name = 'dumbbell deadlift' THEN 'peso muerto con mancuerna'
  WHEN name = 'dumbbell romanian deadlift' THEN 'peso muerto rumano con mancuerna'
  WHEN name = 'leg curl' THEN 'curl de piernas'
  WHEN name = 'lying leg curl' THEN 'curl de piernas acostado'
  WHEN name = 'lying leg curl (male)' THEN 'curl de piernas acostado'
  WHEN name = 'romanian deadlift' THEN 'peso muerto rumano'
  WHEN name = 'seated leg curl' THEN 'curl de piernas sentado'
  WHEN name = 'standing leg curl' THEN 'curl de piernas de pie'
  WHEN name = 'stiff leg deadlift' THEN 'peso muerto piernas rígidas'
  WHEN name = 'straight leg deadlift' THEN 'peso muerto piernas rectas'
  WHEN name = 'weighted hyperextension (male)' THEN 'hiperextensión con peso'
  WHEN name = 'good morning' THEN 'good morning'

  -- Glúteos
  WHEN name = 'band hip lift (male)' THEN 'elevación de cadera con banda'
  WHEN name = 'barbell glute bridge' THEN 'puente de glúteos con barra'
  WHEN name = 'barbell hip thrust' THEN 'empuje de cadera con barra'
  WHEN name = 'cable hip extension' THEN 'extensión de cadera en polea'
  WHEN name = 'donkey kick' THEN 'patada de burro'
  WHEN name = 'fire hydrant' THEN 'boca de incendio'
  WHEN name = 'glute bridge' THEN 'puente de glúteos'
  WHEN name = 'glute kickback' THEN 'patada de glúteo'
  WHEN name = 'hip abduction (male)' THEN 'abducción de cadera'
  WHEN name = 'hip thrust (male)' THEN 'empuje de cadera'
  WHEN name = 'single leg glute bridge' THEN 'puente de glúteos una pierna'
  WHEN name = 'single leg hip thrust' THEN 'empuje de cadera una pierna'

  -- Pantorrillas
  WHEN name = 'ankle circles' THEN 'círculos de tobillo'
  WHEN name = 'assisted lying calves stretch' THEN 'estiramiento de pantorrillas acostado asistido'
  WHEN name = 'calf raise' THEN 'elevación de pantorrillas'
  WHEN name = 'donkey calf raise' THEN 'elevación de pantorrillas de burro'
  WHEN name = 'dumbbell calf raise' THEN 'elevación de pantorrillas con mancuerna'
  WHEN name = 'seated calf raise' THEN 'elevación de pantorrillas sentado'
  WHEN name = 'seated calf raise (male)' THEN 'elevación de pantorrillas sentado'
  WHEN name = 'standing calf raise' THEN 'elevación de pantorrillas de pie'
  WHEN name = 'standing calf raise (male)' THEN 'elevación de pantorrillas de pie'

  -- Cardio
  WHEN name = 'astride jumps (male)' THEN 'saltos de tijera'
  WHEN name = 'back and forth step' THEN 'paso adelante y atrás'
  WHEN name = 'burpee' THEN 'burpee'
  WHEN name = 'double under' THEN 'doble salto'
  WHEN name = 'high knee' THEN 'rodillas arriba'
  WHEN name = 'jump rope' THEN 'saltar la cuerda'
  WHEN name = 'jumping jack' THEN 'saltos de tijera'
  WHEN name = 'lateral shuffle' THEN 'desplazamiento lateral'
  WHEN name = 'mountain climber (male)' THEN 'escalador'
  WHEN name = 'prowler sprint' THEN 'sprint con prowler'
  WHEN name = 'rowing' THEN 'remo'
  WHEN name = 'running' THEN 'correr'
  WHEN name = 'side shuffle' THEN 'desplazamiento lateral'
  WHEN name = 'sprint' THEN 'sprint'
  WHEN name = 'star jump' THEN 'salto estrella'
  WHEN name = 'treadmill' THEN 'cinta de correr'
  WHEN name = 'walking' THEN 'caminar'

  -- Estiramientos
  WHEN name = 'butterfly stretch' THEN 'estiramiento mariposa'
  WHEN name = 'calf stretch' THEN 'estiramiento de pantorrillas'
  WHEN name = 'chest stretch' THEN 'estiramiento de pecho'
  WHEN name = 'child pose' THEN 'postura del niño'
  WHEN name = 'cobra stretch' THEN 'estiramiento cobra'
  WHEN name = 'downward dog' THEN 'perro boca abajo'
  WHEN name = 'figure four stretch' THEN 'estiramiento figura cuatro'
  WHEN name = 'groin stretch' THEN 'estiramiento de ingle'
  WHEN name = 'hamstring stretch' THEN 'estiramiento de femorales'
  WHEN name = 'hip flexor stretch (male)' THEN 'estiramiento de flexores de cadera'
  WHEN name = 'knees to chest' THEN 'rodillas al pecho'
  WHEN name = 'neck stretch' THEN 'estiramiento de cuello'
  WHEN name = 'pigeon pose' THEN 'postura de la paloma'
  WHEN name = 'quad stretch' THEN 'estiramiento de cuádriceps'
  WHEN name = 'shoulder stretch' THEN 'estiramiento de hombros'
  WHEN name = 'spine stretch' THEN 'estiramiento de columna'
  WHEN name = 'standing hamstring stretch' THEN 'estiramiento de femorales de pie'
  WHEN name = 'triceps stretch' THEN 'estiramiento de tríceps'
  WHEN name = 'upper back stretch' THEN 'estiramiento de espalda superior'
  WHEN name = 'world greatest stretch' THEN 'estiramiento del mundo'

  ELSE name
END;

-- 3. Nota: Las descripciones (instructions_es) ya estaban en español
--    Los workout_exercise_logs tienen denormalizado el nombre inglés
--    que se guardó al crear el log, eso no se actualiza aquí.
