import { User, Payment, Staff, Attendance, DashboardStats, PhysicalProgress, Routine, Invoice, RoutineTemplate, UserRoutineAssignment, WorkoutSession } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Carlos Mendoza',
    email: 'carlos.m@email.com',
    phone: '0424-1234567',
    memberNumber: 'GYM-001',
    status: 'Activo',
    plan: 'Premium Mensual',
    startDate: '2024-01-15',
    nextPayment: '2026-03-15',
    weight: 85,
    height: 175,
    imc: 27.8,
  },
  {
    id: '2',
    name: 'María González',
    email: 'maria.g@email.com',
    phone: '0414-7654321',
    memberNumber: 'GYM-002',
    status: 'Activo',
    plan: 'Básico Mensual',
    startDate: '2024-02-01',
    nextPayment: '2026-03-01',
    weight: 62,
    height: 165,
    imc: 22.8,
  },
  {
    id: '3',
    name: 'José Ramírez',
    email: 'jose.r@email.com',
    phone: '0412-9876543',
    memberNumber: 'GYM-003',
    status: 'Moroso',
    plan: 'Premium Mensual',
    startDate: '2023-12-10',
    nextPayment: '2026-02-10',
    weight: 90,
    height: 180,
    imc: 27.8,
  },
  {
    id: '4',
    name: 'Ana Rodríguez',
    email: 'ana.r@email.com',
    phone: '0426-5551234',
    memberNumber: 'GYM-004',
    status: 'Activo',
    plan: 'VIP Trimestral',
    startDate: '2024-01-20',
    nextPayment: '2026-04-20',
    weight: 58,
    height: 160,
    imc: 22.7,
  },
  {
    id: '5',
    name: 'Luis Martínez',
    email: 'luis.m@email.com',
    phone: '0416-7778899',
    memberNumber: 'GYM-005',
    status: 'Activo',
    plan: 'Básico Mensual',
    startDate: '2024-02-10',
    nextPayment: '2026-03-10',
    weight: 78,
    height: 172,
    imc: 26.4,
  },
];

export const mockPayments: Payment[] = [
  {
    id: '1',
    userId: '1',
    userName: 'Carlos Mendoza',
    amount: 450,
    date: '2026-02-15',
    nextPayment: '2026-03-15',
    status: 'Pagado',
    method: 'Transferencia',
  },
  {
    id: '2',
    userId: '2',
    userName: 'María González',
    amount: 300,
    date: '2026-02-01',
    nextPayment: '2026-03-01',
    status: 'Pagado',
    method: 'Efectivo',
  },
  {
    id: '3',
    userId: '3',
    userName: 'José Ramírez',
    amount: 450,
    date: '2026-01-10',
    nextPayment: '2026-02-10',
    status: 'Vencido',
    method: 'Transferencia',
  },
  {
    id: '4',
    userId: '4',
    userName: 'Ana Rodríguez',
    amount: 1200,
    date: '2026-01-20',
    nextPayment: '2026-04-20',
    status: 'Pagado',
    method: 'Tarjeta',
  },
  {
    id: '5',
    userId: '5',
    userName: 'Luis Martínez',
    amount: 300,
    date: '2026-02-10',
    nextPayment: '2026-03-10',
    status: 'Pagado',
    method: 'Efectivo',
  },
];

export const mockStaff: Staff[] = [
  {
    id: '1',
    name: 'Pedro Sánchez',
    role: 'Administrador',
    email: 'pedro.s@gym.com',
    phone: '0424-1112233',
    shift: 'Mañana (6am - 2pm)',
    status: 'Activo',
  },
  {
    id: '2',
    name: 'Laura Pérez',
    role: 'Entrenador',
    email: 'laura.p@gym.com',
    phone: '0414-4445566',
    shift: 'Tarde (2pm - 10pm)',
    status: 'Activo',
  },
  {
    id: '3',
    name: 'Miguel Torres',
    role: 'Recepción',
    email: 'miguel.t@gym.com',
    phone: '0412-7778899',
    shift: 'Mañana (6am - 2pm)',
    status: 'Activo',
  },
  {
    id: '4',
    name: 'Carmen López',
    role: 'Entrenador',
    email: 'carmen.l@gym.com',
    phone: '0426-3334455',
    shift: 'Mañana (6am - 2pm)',
    status: 'Activo',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: '1',
    userId: '1',
    userName: 'Carlos Mendoza',
    date: '2026-02-24',
    time: '06:30',
    type: 'Entrada',
  },
  {
    id: '2',
    userId: '2',
    userName: 'María González',
    date: '2026-02-24',
    time: '07:15',
    type: 'Entrada',
  },
  {
    id: '3',
    userId: '4',
    userName: 'Ana Rodríguez',
    date: '2026-02-24',
    time: '08:00',
    type: 'Entrada',
  },
  {
    id: '4',
    userId: '5',
    userName: 'Luis Martínez',
    date: '2026-02-24',
    time: '09:30',
    type: 'Entrada',
  },
  {
    id: '5',
    userId: '1',
    userName: 'Carlos Mendoza',
    date: '2026-02-23',
    time: '06:45',
    type: 'Entrada',
  },
];

export const mockPhysicalProgress: PhysicalProgress[] = [
  {
    id: '1',
    userId: '1',
    date: '2026-01-15',
    weight: 87,
    bodyFat: 22,
    muscleMass: 65,
  },
  {
    id: '2',
    userId: '1',
    date: '2026-02-15',
    weight: 85,
    bodyFat: 20,
    muscleMass: 67,
  },
  {
    id: '3',
    userId: '2',
    date: '2026-02-01',
    weight: 62,
    bodyFat: 25,
    muscleMass: 45,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalUsers: 156,
  activeUsers: 142,
  delinquentUsers: 14,
  monthlyRevenue: 68500,
  todayAttendance: 87,
  totalStaff: 12,
};

export const monthlyRevenueData = [
  { month: 'Sep', revenue: 52000 },
  { month: 'Oct', revenue: 58000 },
  { month: 'Nov', revenue: 61000 },
  { month: 'Dic', revenue: 65000 },
  { month: 'Ene', revenue: 64500 },
  { month: 'Feb', revenue: 68500 },
];

export const attendanceData = [
  { day: 'Lun', count: 95 },
  { day: 'Mar', count: 102 },
  { day: 'Mié', count: 87 },
  { day: 'Jue', count: 98 },
  { day: 'Vie', count: 110 },
  { day: 'Sáb', count: 75 },
  { day: 'Dom', count: 45 },
];

export const userStatusData = [
  { name: 'Activos', value: 142, color: '#10f94e' },
  { name: 'Morosos', value: 14, color: '#ff3b5c' },
];

export const mockRoutines: Routine[] = [
  {
    id: '1',
    userId: '1',
    name: 'Rutina de Fuerza',
    description: 'Enfocada en desarrollo muscular',
    trainerId: '2',
    trainerName: 'Laura Pérez',
    startDate: '2026-02-01',
    exercises: [
      { id: '1', name: 'Press de Banca', sets: 4, reps: '8-10', notes: 'Descanso 90s' },
      { id: '2', name: 'Sentadillas', sets: 4, reps: '10-12', notes: 'Descanso 90s' },
      { id: '3', name: 'Peso Muerto', sets: 3, reps: '6-8', notes: 'Descanso 2min' },
    ],
  },
  {
    id: '2',
    userId: '2',
    name: 'Rutina Cardio',
    description: 'Enfocada en resistencia cardiovascular',
    trainerId: '4',
    trainerName: 'Carmen López',
    startDate: '2026-02-01',
    exercises: [
      { id: '1', name: 'Cinta de correr', sets: 1, reps: '30min', notes: 'Intensidad media' },
      { id: '2', name: 'Bicicleta estática', sets: 1, reps: '20min', notes: 'Intensidad alta' },
      { id: '3', name: 'Elíptica', sets: 1, reps: '15min', notes: 'Cool down' },
    ],
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    userId: '1',
    userName: 'Carlos Mendoza',
    paymentId: '1',
    amount: 450,
    date: '2026-02-15',
    invoiceNumber: 'FAC-2026-001',
    concept: 'Mensualidad Premium - Febrero 2026',
    status: 'Pagada',
  },
  {
    id: '2',
    userId: '2',
    userName: 'María González',
    paymentId: '2',
    amount: 300,
    date: '2026-02-01',
    invoiceNumber: 'FAC-2026-002',
    concept: 'Mensualidad Básica - Febrero 2026',
    status: 'Pagada',
  },
  {
    id: '3',
    userId: '4',
    userName: 'Ana Rodríguez',
    paymentId: '4',
    amount: 1200,
    date: '2026-01-20',
    invoiceNumber: 'FAC-2026-003',
    concept: 'Trimestre VIP - Ene-Mar 2026',
    status: 'Pagada',
  },
];

export const mockRoutineTemplates: RoutineTemplate[] = [
  {
    id: '1',
    name: 'Rutina de Fuerza para Principiantes',
    description: 'Programa diseñado para desarrollar fuerza base en personas que inician en el gimnasio',
    level: 'Principiante',
    category: 'Fuerza',
    duration: '8 semanas',
    daysPerWeek: 3,
    createdBy: '2',
    createdByName: 'Laura Pérez',
    isActive: true,
    createdAt: '2026-01-15',
    exercises: [
      {
        id: 'ex1',
        name: 'Press de Banca',
        muscleGroup: 'Pecho',
        sets: 3,
        reps: '10-12',
        restTime: '90s',
        weight: 'Barra vacía o 10kg',
        instructions: 'Mantén los pies firmes en el suelo, baja la barra hasta el pecho y empuja hacia arriba controladamente',
        order: 1,
      },
      {
        id: 'ex2',
        name: 'Sentadillas',
        muscleGroup: 'Piernas',
        sets: 3,
        reps: '12-15',
        restTime: '90s',
        weight: 'Barra vacía',
        instructions: 'Baja hasta que los muslos estén paralelos al suelo, mantén la espalda recta',
        order: 2,
      },
      {
        id: 'ex3',
        name: 'Remo con Barra',
        muscleGroup: 'Espalda',
        sets: 3,
        reps: '10-12',
        restTime: '90s',
        weight: '10kg',
        instructions: 'Inclina el torso, tira de la barra hacia el abdomen manteniendo los codos cerca del cuerpo',
        order: 3,
      },
      {
        id: 'ex4',
        name: 'Press Militar',
        muscleGroup: 'Hombros',
        sets: 3,
        reps: '10-12',
        restTime: '90s',
        weight: 'Barra vacía',
        instructions: 'Empuja la barra desde los hombros hasta extender completamente los brazos',
        order: 4,
      },
    ],
  },
  {
    id: '2',
    name: 'Hipertrofia Intermedia',
    description: 'Rutina enfocada en ganancia muscular para nivel intermedio',
    level: 'Intermedio',
    category: 'Hipertrofia',
    duration: '12 semanas',
    daysPerWeek: 4,
    createdBy: '4',
    createdByName: 'Carmen López',
    isActive: true,
    createdAt: '2026-01-10',
    exercises: [
      {
        id: 'ex5',
        name: 'Press Inclinado con Mancuernas',
        muscleGroup: 'Pecho',
        sets: 4,
        reps: '8-10',
        restTime: '120s',
        weight: '12-15kg cada mancuerna',
        instructions: 'Banco inclinado a 30-45 grados, baja las mancuernas hasta sentir estiramiento',
        order: 1,
      },
      {
        id: 'ex6',
        name: 'Peso Muerto',
        muscleGroup: 'Espalda',
        sets: 4,
        reps: '6-8',
        restTime: '180s',
        weight: '40-60kg',
        instructions: 'Mantén la espalda recta, levanta la barra pegada al cuerpo',
        order: 2,
      },
      {
        id: 'ex7',
        name: 'Sentadilla Búlgara',
        muscleGroup: 'Piernas',
        sets: 3,
        reps: '10-12 por pierna',
        restTime: '90s',
        weight: 'Mancuernas 10kg',
        instructions: 'Pie trasero elevado, baja controladamente hasta 90 grados',
        order: 3,
      },
      {
        id: 'ex8',
        name: 'Dominadas',
        muscleGroup: 'Espalda',
        sets: 4,
        reps: '6-10',
        restTime: '120s',
        weight: 'Peso corporal',
        instructions: 'Agarre prono, tira hasta que la barbilla pase la barra',
        order: 4,
      },
    ],
  },
  {
    id: '3',
    name: 'Cardio y Resistencia',
    description: 'Programa cardiovascular para mejorar resistencia y quemar grasa',
    level: 'Intermedio',
    category: 'Cardio',
    duration: '6 semanas',
    daysPerWeek: 5,
    createdBy: '2',
    createdByName: 'Laura Pérez',
    isActive: true,
    createdAt: '2026-02-01',
    exercises: [
      {
        id: 'ex9',
        name: 'Cinta de Correr - Intervalos',
        muscleGroup: 'Cardio',
        sets: 1,
        reps: '20 minutos',
        restTime: '0s',
        instructions: 'Alterna 2 min intensidad alta con 1 min intensidad baja',
        order: 1,
      },
      {
        id: 'ex10',
        name: 'Burpees',
        muscleGroup: 'Cuerpo Completo',
        sets: 3,
        reps: '15-20',
        restTime: '60s',
        weight: 'Peso corporal',
        instructions: 'Movimiento explosivo, desde plancha hasta salto',
        order: 2,
      },
      {
        id: 'ex11',
        name: 'Bicicleta Estática',
        muscleGroup: 'Cardio',
        sets: 1,
        reps: '15 minutos',
        restTime: '0s',
        instructions: 'Mantén ritmo constante a intensidad media-alta',
        order: 3,
      },
      {
        id: 'ex12',
        name: 'Mountain Climbers',
        muscleGroup: 'Core',
        sets: 3,
        reps: '30 segundos',
        restTime: '45s',
        weight: 'Peso corporal',
        instructions: 'Alterna rodillas al pecho rápidamente desde posición de plancha',
        order: 4,
      },
    ],
  },
  {
    id: '4',
    name: 'Full Body Avanzado',
    description: 'Entrenamiento completo de cuerpo entero para atletas avanzados',
    level: 'Avanzado',
    category: 'Funcional',
    duration: '10 semanas',
    daysPerWeek: 4,
    createdBy: '4',
    createdByName: 'Carmen López',
    isActive: true,
    createdAt: '2026-01-20',
    exercises: [
      {
        id: 'ex13',
        name: 'Clean and Press',
        muscleGroup: 'Cuerpo Completo',
        sets: 5,
        reps: '5',
        restTime: '180s',
        weight: '40-50kg',
        instructions: 'Movimiento olímpico, desde el suelo hasta overhead en un movimiento fluido',
        order: 1,
      },
      {
        id: 'ex14',
        name: 'Front Squat',
        muscleGroup: 'Piernas',
        sets: 4,
        reps: '6-8',
        restTime: '150s',
        weight: '50-70kg',
        instructions: 'Barra en posición frontal, codos arriba, baja profundo',
        order: 2,
      },
      {
        id: 'ex15',
        name: 'Muscle Ups',
        muscleGroup: 'Cuerpo Completo',
        sets: 3,
        reps: '5-8',
        restTime: '180s',
        weight: 'Peso corporal',
        instructions: 'De dominada a fondo en anillas o barra',
        order: 3,
      },
    ],
  },
];

export const mockUserRoutineAssignments: UserRoutineAssignment[] = [
  {
    id: '1',
    userId: '1',
    userName: 'Carlos Mendoza',
    routineId: '1',
    routineName: 'Rutina de Fuerza para Principiantes',
    assignedBy: '2',
    assignedByName: 'Laura Pérez',
    startDate: '2026-02-01',
    isActive: true,
  },
  {
    id: '2',
    userId: '2',
    userName: 'María González',
    routineId: '3',
    routineName: 'Cardio y Resistencia',
    assignedBy: '4',
    assignedByName: 'Carmen López',
    startDate: '2026-02-01',
    isActive: true,
  },
];

export const mockWorkoutSessions: WorkoutSession[] = [
  {
    id: '1',
    userId: '1',
    routineId: '1',
    routineName: 'Rutina de Fuerza para Principiantes',
    date: '2026-02-24',
    startTime: '07:00',
    endTime: '08:15',
    isCompleted: true,
    exercises: [
      {
        id: 'log1',
        exerciseId: 'ex1',
        exerciseName: 'Press de Banca',
        muscleGroup: 'Pecho',
        isCompleted: true,
        sets: [
          { id: 's1', setNumber: 1, reps: 12, weight: 20, isCompleted: true },
          { id: 's2', setNumber: 2, reps: 10, weight: 20, isCompleted: true },
          { id: 's3', setNumber: 3, reps: 10, weight: 20, isCompleted: true },
        ],
      },
      {
        id: 'log2',
        exerciseId: 'ex2',
        exerciseName: 'Sentadillas',
        muscleGroup: 'Piernas',
        isCompleted: true,
        sets: [
          { id: 's4', setNumber: 1, reps: 15, weight: 20, isCompleted: true },
          { id: 's5', setNumber: 2, reps: 15, weight: 20, isCompleted: true },
          { id: 's6', setNumber: 3, reps: 12, weight: 20, isCompleted: true },
        ],
      },
    ],
  },
];